version: '3.1'
services:

    mysqldb:
        image: mariadb:latest
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        command: [
            '--wait_timeout=360000',
            ]
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_USER=${MARIADB_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASS}
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mariadb/innodb.cnf:/etc/mysql/conf.d/innodb.cnf:ro"